### ISSUE TITLE
Encryption-modified Storage IO benchmarks

### ISSUE THREAD

**Issue by enterJazz** [TUM-DSE/CVM_eval#14]
Related to #9 - implements `dm-encrypt` of P4 (we may also add SPDK encryption, if available, later)

**Goal:** Add `dm-encrypt` to the benchmark tool.

- this implementation will NOT include integrity protection

**TODOs**:
- [x] enable `dm-crypt`
    - [x] create RAM disk to `cryptsetup` ( can be replaced later w/ different device )
    - [x] point `fio` into said disk
    - see https://blog.cloudflare.com/speeding-up-linux-disk-encryption/ for example
- [x] enable `no_read_workqueue` / `no_write_workqueue` options ( see https://github.com/TUM-DSE/CVM_eval/issues/9#issuecomment-1647815683 ) (we could have this optional as well)
