### ISSUE TITLE
TDX attestation

### ISSUE THREAD

**Issue by mmisono** [TUM-DSE/CVM_eval#67]
Document: https://github.com/canonical/tdx?tab=readme-ov-file#8-setup-remote-attestation-on-host-os-and-inside-td

### TODO
- [x] Host setup
    - [x] Install tools
    - [x] Get a subscription key for the Intel PCS (8.2.6)
    - [x] Configure thee PCCS service (8.2.7)
    - [x] Platform registration (8.2.10)
    - [x] Install SGXDataCenterAttestationPrimitives (or QuoteVefiricationLibrary)
- [x] Guest setup
    - [x] Install tools
    - [ ] ~Get API key for Intel Tiber Turst Service (8.4.3)~
- [x] Check if attestation work (8.4)

### How to test
1. log in to the server
2. `cd ~/work/tdx/guest-tools`
3. Start TD: `./run_td.sh`
4. Login to the guest: `ssh -p 10022 root@localhost`
5. (in the guest): `cd /usr/share/doc/libtdx-attest-dev/examples/`
6. (in the guest): `./test_tdx_attest`
